version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: skillgap_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Omkar1707mysql
      MYSQL_DATABASE: skillgap_advisor
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: skillgap_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/skillgap_advisor?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Omkar1707mysql
    depends_on:
      - mysqldb
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: skillgap_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
